language: r
cache: packages
r_check_args: --as-cran 
r_build_args: --compact-vignettes=both
warnings_are_errors: false

r:
  - release
  - devel

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

before_install:
  - export DISPLAY=:99.0

apt_packages:
  - libgl1-mesa-dev 
  - libglu1-mesa-dev
  - ghostscript
  - qpdf

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  CODECOV_TOKEN="7222539e-bf75-4b93-917f-19934a168b9d"
  
r_packages:
  - covr

after_success:
    - Rscript -e 'covr::codecov()'