texts_pl_df <- read.csv("texts_pl.csv", stringsAsFactors = FALSE)
texts_en_df <- read.csv("texts_en.csv", stringsAsFactors = FALSE)
texts_pl <- as.list(tidyr::spread(texts_pl_df, key, value))
texts_en <- as.list(tidyr::spread(texts_en_df, key, value))
texts = list(en = texts_en, pl = texts_pl)
usethis::use_data(texts, internal = TRUE, overwrite = TRUE)
